kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elixir-pipeline-pvc
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    tekton.dev/pipeline: elixirapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem