kind: Deployment
apiVersion: apps/v1
metadata:
  name: elixirapp
  labels:
    app: elixirapp
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elixirapp
  template:
    metadata:
      labels:
        app: elixirapp
        deployment: elixirapp
    spec:
      containers:
        - name: elixirapp
          image: elixirapp:latest
          env:
            - name: SECRET_KEY_BASE
              value: AlTACgJs61IKbnkKbnyZGeh3qcZE6R7qCCDKp425ptH/wjoqe7Y2EK6wQJWyjMoD
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
